language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalahast/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kalahast/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-708375812816"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY